template: |
  ## Changes

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🏠 Maintenance'
    labels:
      - 'chore'
  - title: '🔨 Refactoring'
    labels:
      - 'refactor'
