name: Generate Vim Documentation

on:
  push:
    branches: [ "master" ]
    paths:
      - 'lua/**'
      - 'README.md'
      - 'doc/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'lua/**'
      - 'README.md'
      - 'doc/**'

jobs:
  vim-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check vim documentation
        run: |
          echo "📖 Checking vim documentation..."
          if [ -f "doc/codecompanion-spinner.txt" ]; then
            echo "✅ Vim help file exists: doc/codecompanion-spinner.txt"
            head -10 doc/codecompanion-spinner.txt
          else
            echo "❌ Vim help file not found"
            exit 1
          fi

      - name: Validate documentation structure
        run: |
          echo "🔍 Validating documentation structure..."
          # Check if the vim help file has proper structure
          if grep -q "*codecompanion-spinner*" doc/codecompanion-spinner.txt; then
            echo "✅ Vim help file has proper tag structure"
          else
            echo "⚠️  Vim help file may be missing proper tags"
          fi