name: Lint & Format Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
          args: --check .

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        env:
          LUA_PATH: "./lua/?.lua;./tests/?.lua"
        run: luacheck lua/ tests/ --globals vim describe it before_each after_each setup teardown context --ignore 611 612 613 614
