name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.neovim_version == 'nightly' }}
    strategy:
      matrix:
        neovim_version: ["v0.9.5", "nightly"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install Dependencies
        run: make install-deps

      - name: Run Tests
        run: make test
